---

- name: Upload certificate file.
  connection: httpapi
  fortinet.fortiweb.fwebos_certificate_local_import_certificate:
    action: add
    vdom: "{{ fortiweb_certificate_vdom | default('root') }}"
    type: certificate
    certificateFile: "{{ item.certificate_file }}"
    keyFile: "{{ item.private_key }}"
    password: ""
    hsm: ""
  changed_when: false
  loop: "{{ fortiweb_certificates }}"
  loop_control:
    label: "{{ item.domain }}"
