---

- name: Run pre-tasks.
  ansible.builtin.import_tasks: 00-pre-tasks.yaml

- name: Upload SSL certificates.
  ansible.builtin.import_tasks: 01-upload-certificate.yaml

- name: Upload intermediate certificates.
  ansible.builtin.include_tasks: 02-upload-intermediate-certificate.yaml
  loop: "{{ fortiweb_certificates | unique(attribute='domain') }}"
  loop_control:
    label: "{{ item.domain }}"

- name: Add certificate to server policy.
  ansible.builtin.import_tasks: 03-add-certificate-to-server.yaml
